//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerCommissionWebApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Broker_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Broker_Master()
        {
            this.Client_Memo_Broker = new HashSet<Client_Memo_Broker>();
            this.Statement_Details = new HashSet<Statement_Details>();
        }
    
        public int ID { get; set; }
        public string BROKER_NAME { get; set; }
        public string PAYLOCITY_ID { get; set; }
        public Nullable<decimal> PREMIUM { get; set; }
        public string EMAIL { get; set; }
        public string SECONDARY_EMAIL { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> PREMIUM_TH { get; set; }
        public string NOTES { get; set; }
        public string BROKER_STATUS { get; set; }
        public string BROKER_NAME_ID { get; set; }
        public string BROKER_NAME_1 { get; set; }
        public string BROKER_NAME_2 { get; set; }
        public string BROKER_NAME_3 { get; set; }
        public string BROKER_NAME_4 { get; set; }
        public string BROKER_NAME_5 { get; set; }
        public string BROKER_NAME_6 { get; set; }
        public string BROKER_NAME_ID_FORMATTED { get; set; }
        public string BROKER_NAME_FORMATTED { get; set; }
        public string BROKER_NAME_1_FORMATTED { get; set; }
        public string BROKER_NAME_2_FORMATTED { get; set; }
        public string BROKER_NAME_3_FORMATTED { get; set; }
        public string BROKER_NAME_4_FORMATTED { get; set; }
        public string BROKER_NAME_5_FORMATTED { get; set; }
        public string BROKER_NAME_6_FORMATTED { get; set; }
        public System.DateTime created_at { get; set; }
        public string created_by { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_Memo_Broker> Client_Memo_Broker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Statement_Details> Statement_Details { get; set; }
    }
}
