//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerCommissionWebApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BROKER_CLIENT
    {
        public int ID { get; set; }
        public string BROKER_NAME { get; set; }
        public string QB_BROKER_NAME { get; set; }
        public string CLIENT_NAME { get; set; }
        public string QB_FEE { get; set; }
        public string BROKER_STATUS { get; set; }
        public string EMAIL { get; set; }
        public string QB_CLIENT_NAME { get; set; }
        public string FEE_MEMO { get; set; }
        public Nullable<decimal> COMMISSION_RATE { get; set; }
        public string UNIT { get; set; }
        public string PAYLOCITY_ID { get; set; }
        public string SECONDARY_EMAIL { get; set; }
        public string BROKER_NAME_1 { get; set; }
        public string BROKER_NAME_2 { get; set; }
        public string BROKER_NAME_3 { get; set; }
        public string BROKER_NAME_4 { get; set; }
        public string BROKER_NAME_5 { get; set; }
        public string BROKER_NAME_6 { get; set; }
        public string START_DATE { get; set; }
    }
}
