//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerCommissionWebApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BROKER_GROUP
    {
        public int ID { get; set; }
        public string BROKER_GROUP1 { get; set; }
        public string AGENT { get; set; }
        public Nullable<int> AGENT_ID { get; set; }
        public string TITLE { get; set; }
        public System.DateTime created_at { get; set; }
        public string created_by { get; set; }
    }
}
