//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerCommissionWebApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Broker_Master_
    {
        public int ID { get; set; }
        public string BROKER_NAME { get; set; }
        public Nullable<int> BROKER_GROUP { get; set; }
        public Nullable<int> PREMIUM { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string EMAIL { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> PREMIUM_TH { get; set; }
        public string NOTES { get; set; }
        public Nullable<int> PAYLOCITY_ID { get; set; }
        public string BROKER_NAME_ID { get; set; }
        public System.DateTime created_at { get; set; }
        public string created_by { get; set; }
    }
}
