//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerCommissionWebApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Client_Memo_Broker = new HashSet<Client_Memo_Broker>();
        }
    
        public int CLIENT_ID { get; set; }
        public string QB_CLIENT_NAME { get; set; }
        public string CLIENT_NAME { get; set; }
        public string STATUS { get; set; }
        public string QB_CLIENT_NAME_FORMATTED { get; set; }
        public System.DateTime created_at { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_Memo_Broker> Client_Memo_Broker { get; set; }
    }
}
