//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerCommissionWebApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Memo_Broker
    {
        public int CLIENT_ID { get; set; }
        public string MEMO { get; set; }
        public int BROKER_ID { get; set; }
        public Nullable<decimal> COMMISSION_RATE { get; set; }
        public string UNIT { get; set; }
        public string STATUS { get; set; }
        public string FEE { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public System.DateTime created_at { get; set; }
        public string created_by { get; set; }
        public string MEMO_FORMATTED { get; set; }
    
        public virtual Broker_Master Broker_Master { get; set; }
        public virtual Client Client { get; set; }
        public virtual Fee_Memo Fee_Memo { get; set; }
    }
}
