//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerCommissionWebApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEE_MEMO
    {
        public int ID { get; set; }
        public string MEMO { get; set; }
        public Nullable<int> COMMISIONABLE { get; set; }
        public Nullable<int> CLIENT_ID { get; set; }
        public string NOTE { get; set; }
        public Nullable<decimal> RATE { get; set; }
    }
}
