//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerCommissionWebApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sent_Invoice
    {
        public int ID { get; set; }
        public string INVOICE_NUM { get; set; }
        public Nullable<decimal> OPEN_BALANCE { get; set; }
        public decimal COMMISSION_PAID { get; set; }
        public string INVOICE_NUM_FORMATTED { get; set; }
        public string month { get; set; }
        public int year { get; set; }
        public System.DateTime DATE_PAID { get; set; }
        public int BROKER_ID { get; set; }
        public System.DateTime created_at { get; set; }
        public string created_by { get; set; }
    }
}
