//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerCommissionWebApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statement_Header
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Statement_Header()
        {
            this.Statement_Details = new HashSet<Statement_Details>();
        }
    
        public int HEADER_ID { get; set; }
        public string MONTH { get; set; }
        public int YEAR { get; set; }
        public Nullable<int> BROKER_ID { get; set; }
        public string BROKER_NAME { get; set; }
        public int FLAG { get; set; }
        public decimal STATEMENT_TOTAL { get; set; }
        public Nullable<System.DateTime> Change_Date { get; set; }
        public decimal STATEMENT_PENDING_TOTAL { get; set; }
        public decimal STATEMENT_ALREADY_PAID_TOTAL { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<int> PAYLOCITY_ID { get; set; }
        public decimal STATEMENT_PROCESSED_THIS_PERIOD { get; set; }
        public System.DateTime created_at { get; set; }
        public string created_by { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Statement_Details> Statement_Details { get; set; }
    }
}
