//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerCommissionWebApp.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Broker_CommissionEntities : DbContext
    {
        public Broker_CommissionEntities()
            : base("name=Broker_CommissionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<Nullable<decimal>> GET_TOTAL(Nullable<int> bid)
        {
            var bidParameter = bid.HasValue ?
                new ObjectParameter("bid", bid) :
                new ObjectParameter("bid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("GET_TOTAL", bidParameter);
        }
    
        public virtual ObjectResult<SP_FILE_IMPORT_SSIS_Result> SP_FILE_IMPORT_SSIS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_FILE_IMPORT_SSIS_Result>("SP_FILE_IMPORT_SSIS");
        }
    
        public virtual int SP_IMPORT_FILE_SENT_SSIS(string month, Nullable<int> year)
        {
            var monthParameter = month != null ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(string));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_IMPORT_FILE_SENT_SSIS", monthParameter, yearParameter);
        }
    
        public virtual int SP_BU_PREVIOUSTABLE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_BU_PREVIOUSTABLE");
        }
    
        public virtual int SP_STATEMENT_DETAIL_UPDATE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_STATEMENT_DETAIL_UPDATE");
        }
    
        public virtual int SP_UPLODADFILE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPLODADFILE");
        }
    }
}
