//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerCommissionWebApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Client_Memo_Broker
    {
        public int CLIENT_ID { get; set; }
        public string CLIENT_NAME { get; set; }
        public Nullable<decimal> COMMISSION_RATE { get; set; }
        public string UNIT { get; set; }
        public string STATUS { get; set; }
        public int BROKER_ID { get; set; }
        public string BROKER_NAME { get; set; }
        public string PAYLOCITY_ID { get; set; }
        public string MEMO { get; set; }
        public Nullable<int> COMMISIONABLE { get; set; }
    }
}
