use Broker_Commission;

/* B. code calls SP_IMPORT_FILE_SENT_SSIS */
EXEC [dbo].[SP_IMPORT_FILE_SENT_SSIS] @Month='March' , @Year='2022';

/* inserts into statement header from COMMISSION_SUMMARY - one row per bromker with totals
     RT.[BROKER_ID]
                  , RT.[BROKER_NAME]
                  , RT.PAYLOCITY_ID, total(COMMISSION AMOUNT)
   
   ( CASE
	WHEN BC.UNIT ='Per Qt' THEN BC.COMMISSION_RATE * OCT.Qty
	WHEN BC.UNIT ='Per Amount'  THEN BC.COMMISSION_RATE * OCT.Amount
	WHEN BC.UNIT ='Flat Rate'  THEN BC.COMMISSION_RATE
	END ) AS [COMMISSION AMOUNT]
   
   deletes
   */
go

select *
from
    dbo.COMMISSION_SUMMARY;

select *
from
    [STATEMENT_HEADER];
go

go
/* WHERE LTRIM(RTRIM(UPPER(BC.QB_BROKER_NAME))) != ''  AND OCT.ID IS NOT NULL */
select *
from
    [dbo].[COMMISSION_RESULT_NAME0];

/* WHERE LTRIM(RTRIM(UPPER(BC.BROKER_NAME_3))) != ''  AND BC.BROKER_NAME_3 IS NOT NULL AND OCT.ID IS NOT NULL */
select *
from
    [dbo].[COMMISSION_RESULT_NAME1];

/* WHERE LTRIM(RTRIM(UPPER(BC.BROKER_NAME_1))) != ''  AND BC.BROKER_NAME_1 IS NOT NULL AND OCT.ID IS NOT NULL */
select *
from
    [dbo].[COMMISSION_RESULT_NAME2];

/* WHERE LTRIM(RTRIM(UPPER(BC.BROKER_NAME_2))) != ''  AND BC.BROKER_NAME_2 IS NOT NULL AND OCT.ID IS NOT NULL*/
select *
from
    [dbo].[COMMISSION_RESULT_NAME3];

/* WHERE LTRIM(RTRIM(UPPER(BC.BROKER_NAME_4))) != ''  AND BC.BROKER_NAME_4 IS NOT NULL AND OCT.ID IS NOT NULL */
select *
from
    [dbo].[COMMISSION_RESULT_NAME4];

/* WHERE LTRIM(RTRIM(UPPER(BC.BROKER_NAME_5))) != ''  AND BC.BROKER_NAME_5 IS NOT NULL AND OCT.ID IS NOT NULL */
select *
from
    [dbo].[COMMISSION_RESULT_NAME5];

/* WHERE LTRIM(RTRIM(UPPER(BC.BROKER_NAME_6))) != ''  AND BC.BROKER_NAME_6 IS NOT NULL AND OCT.ID IS NOT NULL */
select *
from
    [dbo].[COMMISSION_RESULT_NAME6];

/*
 SELECT * FROM [dbo].[COMMISSION_RESULT_NAME0]
	 UNION
	 SELECT * FROM [dbo].[COMMISSION_RESULT_NAME1]
	 UNION
	 SELECT * FROM [dbo].[COMMISSION_RESULT_NAME2]
	 UNION
	 SELECT * FROM [dbo].[COMMISSION_RESULT_NAME3]
	 UNION
	 SELECT * FROM [dbo].[COMMISSION_RESULT_NAME4]
	  UNION
	 SELECT * FROM [dbo].[COMMISSION_RESULT_NAME5]
	  UNION
	 SELECT * FROM [dbo].[COMMISSION_RESULT_NAME6]
	 UNION
        select x FROM [dbo].[STATEMENT_DETAILS_ADD]
*/
select *
from
    dbo.COMMISSION_RESULT;

/* B. UI clicks View Upload Results */
;


