//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerCommissionWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMISSION_SUMMARY
    {
        public int BROKER_ID { get; set; }
        public string BROKER_NAME { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public string PAYLOCITY_ID { get; set; }
    }
}
