//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Broker_Commission
{
    using System;
    using System.Collections.Generic;
    
    public partial class SENT_INVOICE
    {
        public int ID { get; set; }
        public string INVOICE_NUM { get; set; }
        public Nullable<decimal> OPEN_BALANCE { get; set; }
        public System.DateTime DATE_ENTER { get; set; }
    }
}
