//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Broker_Commission
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Broker_CommissionEntities : DbContext
    {
        public Broker_CommissionEntities()
            : base("name=Broker_CommissionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BROKER_COMMISSION> BROKER_COMMISSION { get; set; }
        public DbSet<BROKER_MASTER> BROKER_MASTER { get; set; }
        public DbSet<BROKER_MASTER_> BROKER_MASTER_ { get; set; }
        public DbSet<CLIENT> CLIENTs { get; set; }
        public DbSet<FEE_MEMO> FEE_MEMO { get; set; }
        public DbSet<STATEMENT_HEADER> STATEMENT_HEADER { get; set; }
        public DbSet<BROKER_GROUP> BROKER_GROUP { get; set; }
        public DbSet<BROKER_CLIENT> BROKER_CLIENT { get; set; }
        public DbSet<COMMISSION_RESULT_NAME0> COMMISSION_RESULT_NAME0 { get; set; }
        public DbSet<COMMISSION_RESULT_NAME1> COMMISSION_RESULT_NAME1 { get; set; }
        public DbSet<COMMISSION_RESULT_NAME2> COMMISSION_RESULT_NAME2 { get; set; }
        public DbSet<COMMISSION_RESULT_NAME3> COMMISSION_RESULT_NAME3 { get; set; }
        public DbSet<COMMISSION_RESULT_NAME4> COMMISSION_RESULT_NAME4 { get; set; }
        public DbSet<COMMISSION_RESULT_NAME5> COMMISSION_RESULT_NAME5 { get; set; }
        public DbSet<COMMISSION_RESULT_NAME6> COMMISSION_RESULT_NAME6 { get; set; }
        public DbSet<COMMISSION_SUMMARY> COMMISSION_SUMMARY { get; set; }
        public DbSet<DASH_BOARD> DASH_BOARD { get; set; }
        public DbSet<VW_STATEMENT> VW_STATEMENT { get; set; }
        public DbSet<CLIENT_> CLIENT_ { get; set; }
        public DbSet<STATEMENT_DETAILS_ADD> STATEMENT_DETAILS_ADD { get; set; }
        public DbSet<Import_OCT> Import_OCT { get; set; }
        public DbSet<STATEMENT_DETAILS> STATEMENT_DETAILS { get; set; }
        public DbSet<Error_Msg> Error_Msg { get; set; }
    
        public virtual ObjectResult<Nullable<decimal>> GET_TOTAL(Nullable<int> bid)
        {
            var bidParameter = bid.HasValue ?
                new ObjectParameter("bid", bid) :
                new ObjectParameter("bid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("GET_TOTAL", bidParameter);
        }
    
        public virtual ObjectResult<SP_FILE_IMPORT_SSIS_Result> SP_FILE_IMPORT_SSIS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_FILE_IMPORT_SSIS_Result>("SP_FILE_IMPORT_SSIS");
        }
    
        public virtual int SP_IMPORT_FILE_SENT_SSIS(string month, Nullable<int> year)
        {
            var monthParameter = month != null ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(string));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_IMPORT_FILE_SENT_SSIS", monthParameter, yearParameter);
        }
    }
}
