CREATE TABLE [dbo].[BROKER_GROUP] (
    [ID]           INT           IDENTITY (1, 1) NOT NULL,
    [BROKER_GROUP] VARCHAR (50)  NULL,
    [AGENT]        VARCHAR (500) NULL,
    [AGENT_ID]     INT           NULL,
    [TITLE]        NVARCHAR (50) NULL
);


GO
CREATE NONCLUSTERED INDEX [AGENT_ID]
    ON [dbo].[BROKER_GROUP]([AGENT_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [BROKER_GROUP]
    ON [dbo].[BROKER_GROUP]([BROKER_GROUP] ASC);


GO
CREATE NONCLUSTERED INDEX [AGENT]
    ON [dbo].[BROKER_GROUP]([AGENT] ASC);

